"""initial migration

Revision ID: 384aa1225433
Revises: None
Create Date: 2014-11-09 17:36:30.587193

"""

# revision identifiers, used by Alembic.
revision = '384aa1225433'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
